# Generated by Django 4.0.3 on 2022-08-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_alter_passport_internal_alter_passport_normal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ready',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.IntegerField()),
                ('ready', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pappers',
        ),
        migrations.AddField(
            model_name='moving',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staying',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
    ]
