# Generated by Django 4.0.3 on 2022-08-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_ready_delete_pappers_moving_confirm_passport_confirm_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ready',
            new_name='Ready1',
        ),
    ]
