# Generated by Django 4.0.3 on 2022-08-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_paper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='moving',
            new_name='papers',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='staying',
        ),
    ]
