# Generated by Django 4.0.3 on 2022-08-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_rename_moving_paper_papers_remove_paper_passport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaperStaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papers', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Paper',
            new_name='PaperMoving',
        ),
    ]
